version: '2'

services:

  app:
    environment:
      # pick db details from environment variables
      - DATABASE_URL=postgres://${USURVEY_DB_USER}:${USURVEY_DB_PASS}@db/${USURVEY_DB}
      - REDIS_HOST=redis_server
      - USURVEY_DB_HOST=db
      - USURVEY_DB
      - USURVEY_DB_USER
      - USURVEY_DB_PASS
    image: antsmc2/usurvey
    command: gunicorn -b 0.0.0.0:8080 --workers=8 --max-requests 1000 --timeout 120 mics.wsgi
    depends_on:
      - redis_server
      - db
    ports:
      - "8080:8080"

  db:
    environment:
      # pls replace with your own values
      POSTGRES_DB: ${USURVEY_DB}
      POSTGRES_USER: ${USURVEY_DB_USER}
      POSTGRES_PASSWORD: ${USURVEY_DB_PASS}
    restart: always
    image: postgres:alpine
    ports:
      - "5430:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data

  redis_server:
    restart: always
    image: redis:alpine
    ports:
      - "6378:6379"
