site_name: uSurvey
pages:
- Home: index.md
- Getting Started: installation.md
- User Manual: user_manual.md
- Offline Data Collection: odk_guide.md
- USSD Integration: ussd-integration.md
- Deployment Guide: deployment_guide.md
- Tests: tests.md
#theme: readthedocs
theme: cerulean
