site_name: uSurvey
pages:
Site Map:
- Site_Map.md
User Guides:
- uSurvey_manual.md
Groups: 
- Groups.md
Modules:
- Modules.md
Listing:
- Listing.md
Survey:
- Survey.md
#theme: readthedocs
theme: cerulean
